name: Build

on: [push, pull_request]

jobs:
  appimage:
    name: AppImage
    runs-on: ubuntu-18.04
    steps:
      - name: Install dependencies
        run: |
          sudo add-apt-repository -y ppa:gnuradio/gnuradio-releases
          sudo apt-get update -qq
          sudo apt-get install -y --no-install-recommends cmake qt5-default qt5-gtk-platformtheme qttranslations5-l10n libqt5svg5-dev libboost-dev libpulse-dev portaudio19-dev liblog4cpp5-dev gnuradio-dev libairspy-dev libairspyhf-dev libfreesrp-dev libhackrf-dev librtlsdr-dev libsoapysdr-dev soapysdr-module-remote libuhd-dev liborc-0.4-dev libhidapi-dev

          cd /tmp
          git clone https://github.com/Nuand/bladeRF.git
          cd bladeRF
          mkdir build
          cd build
          cmake -DCMAKE_INSTALL_PREFIX=/usr ..
          make
          sudo make install
          sudo ldconfig

          cd /tmp
          git clone https://github.com/dl1ksv/gr-fcdproplus.git
          cd gr-fcdproplus
          mkdir build
          cd build
          cmake -DCMAKE_INSTALL_PREFIX=/usr ..
          make
          sudo make install
          sudo ldconfig

          cd /tmp
          git clone git://git.osmocom.org/libosmo-dsp
          cd libosmo-dsp
          autoreconf -i
          ./configure --prefix=/usr
          make
          sudo make install
          sudo ldconfig

          cd /tmp
          git clone git://git.osmocom.org/gr-iqbal
          cd gr-iqbal
          git checkout gr3.8
          mkdir build
          cd build
          cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_MODULES_DIR=/usr/lib/x86_64-linux-gnu/cmake ..
          make
          sudo make install
          sudo ldconfig

          cd /tmp
          git clone git://git.osmocom.org/gr-osmosdr
          cd gr-osmosdr
          git checkout gr3.8
          mkdir build
          cd build
          cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_MODULES_DIR=/usr/lib/x86_64-linux-gnu/cmake ..
          make
          sudo make install
          sudo ldconfig
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Configure
        run: mkdir build && cd build && cmake ..
      - name: Compile
        working-directory: build
        run: make
      - name: Build AppImage
        run: ./appimage.sh
      - name: Save artifact
        uses: actions/upload-artifact@v2
        with:
          name: gqrx-appimage-${{ github.run_id }}
          path: Gqrx-*.AppImage
  macos:
    name: MacOS
    runs-on: macos-10.15
    steps:
      - name: Install dependencies
        run: |
          brew update
          brew install --HEAD --build-from-source dylibbundler portaudio
          brew install airspy boost gnuradio hackrf libbladerf librtlsdr pybind11 uhd
          brew tap pothosware/homebrew-pothos
          brew install soapysdr soapyremote

          cd /tmp
          git clone https://github.com/airspy/airspyhf.git
          cd airspyhf
          mkdir build
          cd build
          cmake ..
          make
          make install

          cd /tmp
          git clone https://github.com/analogdevicesinc/libiio.git
          cd libiio
          mkdir build
          cd build
          cmake ..
          sudo make install

          cd /tmp
          git clone https://github.com/analogdevicesinc/libad9361-iio.git
          cd libad9361-iio
          mkdir build
          cd build
          cmake ..
          sudo make install

          cd /tmp
          git clone https://github.com/pothosware/SoapyPlutoSDR.git
          cd SoapyPlutoSDR
          mkdir build
          cd build
          cmake ..
          make install

          cd /tmp
          cp /Library/Frameworks/iio.framework/iio /usr/local/lib/libiio.dylib
          install_name_tool -id "/usr/local/lib/libiio.dylib" /usr/local/lib/libiio.dylib
          cp /Library/Frameworks/ad9361.framework/ad9361 /usr/local/lib/libad9361.dylib
          install_name_tool -id "/usr/local/lib/libad9361.dylib" /usr/local/lib/libad9361.dylib
          install_name_tool -delete_rpath /Library/Frameworks /usr/local/lib/libad9361.dylib
          install_name_tool -change @rpath/iio.framework/Versions/0.21/iio /usr/local/lib/libiio.dylib /usr/local/lib/libad9361.dylib
          install_name_tool -change @rpath/iio.framework/Versions/0.21/iio /usr/local/lib/libiio.dylib /usr/local/lib/SoapySDR/modules0.*/libPlutoSDRSupport.so
          install_name_tool -change @rpath/ad9361.framework/Versions/0.2/ad9361 /usr/local/lib/libad9361.dylib /usr/local/lib/SoapySDR/modules0.*/libPlutoSDRSupport.so

          cd /tmp
          git clone git://git.osmocom.org/gr-osmosdr
          cd gr-osmosdr
          mkdir build
          cd build
          cmake ..
          LIBRARY_PATH=/usr/local/opt/icu4c/lib make
          make install
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Configure
        run: mkdir build && cd build && cmake ..
      - name: Compile
        working-directory: build
        run: make
      - name: Build DMG
        run: ./macos_bundle.sh
      - name: Save artifact
        uses: actions/upload-artifact@v2
        with:
          name: gqrx-macos-${{ github.run_id }}
          path: Gqrx-*.dmg
